Cherry pick of 361eac12074e480d26c23d6f2eba704a18515f2d failed
stdout:

stderr:

Error: could not apply 361eac12074... [IMP] website, web_tour: have steps to select shape or color
Hint: after resolving the conflicts, mark the corrected paths
Hint: with 'git add <paths>' or 'git rm <paths>'
Hint: and commit the result with 'git commit'
X-original-commit: 59f23ab74fc64bd9192ad69dd329fd7603542efb