[FIX] account: Remove supplier/customer in default_partner_type
The fields supplier/customer was removed from the partner, then, they
cannot be used in the default for the views.

Avoid the next traceback in the next case:
'''raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'supplier' in leaf "<osv.ExtendedLeaf: ('supplier', '=', True) on res_partner (ctx: )>"```

1. Go to create a new payment for supplier
2. Try select the supplier

closes odoo/odoo#35743

Signed-off-by: Yannick Tivisse (yti) <yti@odoo.com>