[FIX] sale: display correct order line value
To reproduce the error:
(Need sale_management)
1. In Settings:
    - Line Subtotals Tax Display: Tax-Included
2. Create a tax T:
    - Included in Price: True
3. Create and save a SO
    - Add a line with T
4. Switch to mobile view

Error: The amount of the order line is incorrect, it does not consider
the option from step 1.

OPW-2484646

closes odoo/odoo#69737

X-original-commit: 4c46522c90aa4cb4c76dc449bb960f429eebff92
Signed-off-by: Adrien Widart <adwid@users.noreply.github.com>