[FIX] phone_validation: fix MRO issue with phone.validation.mixin
Issue is that when a model inherits from phone.Validation.mixin, then from
mail.thread.phone (which inherits from phone.validation.mixin) we have
an issue :

TypeError: Cannot create a consistent method resolution
order (MRO) for bases BaseModel, base, mail.thread, phone.validation.mixin,
mail.thread.phone

As fixing it could be complicated we have a way to avoid it: move conflicting
code as it is used only in mail.thread.phone .

In this commit we also import a file forgotten at 8815065c14336e775b23e4ba6c178e71c2a85166 which triggers
the issue itself.

Task 2063049 (bug spotted)
Task 2061765 (triggering the issue)

closes odoo/odoo#36580

Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>