Revert "[FIX] models: in `onchange`, add missing fields when comparing values"
This reverts commit 134c8f1dfbe047fe99f79ca3b4876c9253a3b02c.

This revision leads to a crash when creating a new user:

Traceback (most recent call last):
  File "/home/dle/odoo/9/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/dle/odoo/9/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/home/dle/odoo/9/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/dle/odoo/9/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/dle/odoo/9/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/dle/odoo/9/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/home/dle/odoo/9/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/home/dle/odoo/enterprise-9/web/controllers/main.py", line 907, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/dle/odoo/enterprise-9/web/controllers/main.py", line 899, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/dle/odoo/9/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/dle/odoo/9/openerp/api.py", line 369, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/dle/odoo/9/openerp/models.py", line 5998, in onchange
    record.mapped(name)
  File "/home/dle/odoo/9/openerp/models.py", line 5497, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/home/dle/odoo/9/openerp/models.py", line 5477, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/home/dle/odoo/9/openerp/models.py", line 5715, in __getitem__
    return self._fields[key].__get__(self, type(self))
KeyError: u'in_group_18'