[FIX] hw_scale: added field 'disable' to namedtuple 'ScaleProtocol'
Introduced at 4d86657bc30
Getting error
TypeError: __new__() got an unexpected keyword argument 'disable'

closes odoo/odoo#28202