[FIX] account: create taxes at reconciliation
- Create an excluded tax of 20 %
- Create a customer invoice of 1000
- Create a payment of 900
- Make the matching between the invoice and the payment:
  Write-off of 83.33, with the 20 % tax

Error: 'Cannot create unbalanced journal entry'

After commit a5e23fea4a5c46c50e6a, the tax are by default not created
automatically anymore. We should make sure to pass the context key
`apply_taxes`.

opw-744266