[FIX] sale_stock_margin: use data of SOL's company
In a multi-company and multi-currency environment, the computation of
the purchase price may be based on the incorrect company (and thus lead
to incorrect results)

To reproduce the issue:
(Use demo data)
1. In Settings:
    - Enable "Multi-Currencies"
2. Update "My Company (Chicago)":
    - Currency: EUR
3. Edit currencies' rate for all companies(!):
    - USD: 1.0
    - EUR: 3.0
4. Create a product category PC:
    - Costing Method: FIFO
5. Create a product P:
    - Type: Storable
    - Category: PC
6. Switch to "My Company (Chicago)"
    - Note that in this company, the costing method of PC is "Standard
Price"
7. Edit P:
    - Cost: 10
8. Create a sale order SO:
    - Pricelist: EUR
    - Lines (add Cost columns):
        - 1 x P (Note that cost is 10€)
9. Confirm SO

Error: The sale order line is incorrect, the cost is now 30€. A rate
conversion has been applied on the amount

In `_compute_purchase_price`, several fields/methods depend on the SOL's
company: `property_cost_method`, `_compute_average_price`,
`cost_currency_id`. Therefore, we should include this specific company
in the environment of the product

OPW-2659265

closes odoo/odoo#79350

X-original-commit: 3f727f0c3fb23894905215840ff832d6630ae2e1
Signed-off-by: Steve Van Essche <svs@odoo.com>
Signed-off-by: Adrien Widart <awt@odoo.com>