[FIX] sale_stock: consider state on qty_at_date widget update
When adding a line to a new SO, if the delivery date is in the future,
and even though the quantity will be sufficient at that time, the
symbol of the quantity remains red ("Not available").

To reproduce the error:
1. Create a storable product P
2. Create + Confirm a RfQ
    - Add 1 x P
    - Set the receipt date in the future (e.g., today + 7 days)
    - (! Do not receive the product)
3. Create a SO
    - Add 1 x P
    - (In Other Info) Set the delivery date after the receipt date
(e.g., today + 8 days)
4. Save & Go back to order lines

Error: The chart next to the requested quantity is always red. This is
not true since the delivery is scheduled after the product reception. If
you click on the chart, the forcasted stock on delivery date is 1.
Therefore, the chart should be green.

This fix improves #60054: the latter updates the computation of
`will_be_fulfilled` using `free_qty_today` because there was an issue
when the SO is confirmed. However, the initial widget behaviour was
correct when the SO is not confirmed.

OPW-2440724

closes odoo/odoo#66101

X-original-commit: 1bf6b368ccfdc91b6168eefd5ff9beb632e8b772
Signed-off-by: Adrien Widart <adwid@users.noreply.github.com>