[FIX] payment_paypal: pdt parsing - accept error as response
In case of error, paypal return some lines where error message and not a
string with 'key=value'.

This commit fix traceback:
ValueError: dictionary update sequence element #0 has length 1; 2 is required